spring.application.name=IssueTracker

server.port=${port:8080}

spring.datasource.url=jdbc:postgresql://localhost:5432/issue_tracker
spring.datasource.username=moiseyev_ilya
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

logging.level.root=INFO
logging.level.com.moiseyev.issuetracker=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.file.name=logs/IssueTracker.log

security.jwt.expiration-ms=86400000
security.jwt.secret=EJydtCyp03xn8vOO4B8SeVWCE7EMe3yze4bByxXSx7temGADP9qhdniUWvrC0Sw0i5WNGOuo1SYu8NvTJ3YPX3