DROP TABLE IF EXISTS attachments;

ALTER TABLE issue_tags DROP CONSTRAINT issue_tags_pkey;
ALTER TABLE issue_tags
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE issue_tags
    ADD CONSTRAINT uk_issue_tag UNIQUE (issue_id, tag_id);